### PR TITLE
Adds basic radio support

### PR DESCRIPTION
**Pull request by cfangmeier**
Adds ability to queue songs based on a newly created radio station. It's a bit hacky, but it works. It adds a new command `radio` which just creates a new radio station based on the supplied album/artist/song and replaces the queue w/ songs from the station.

Addresses the radio part of issue #24 .

### CODE REVIEW

**Comment by christopher-dG** [comment]
This is fantastic, thanks! This covers the auto-generated stations, but I'm also hoping to have the named stations. I'm going to leave this open until I have a bit of spare time to do that part myself. 

In the meantime, I'd recommend that you fix your commits so that you're properly credited,  if looks like your email might be set incorrectly :slightly_smiling_face: :

**Comment by cfangmeier** [comment]
Sounds good. One of the issues I ran into on this was how to handle queues that are too long to fit on the screen. Especially w/ radio stations, it would be nice to queue up hours of songs in one go and be free to look at the queue far ahead(just as you can do in the browser). One could, for example, add a key binding to move the view up and down the list of queued songs, but I think this might require quite some changes in how the screen is handled. In any case, this is a separate issue.

**Comment by christopher-dG** [comment]
Yep, I've also encountered that problem. I was not very familiar with ncurses manipulation when I first wrote the screen code, so that's definitely something I'd like to rework but as you said, it's a separate task and will take more time.

**Comment by christopher-dG** [comment]
On second thought I've begun a pretty significant rewrite, so I'm gonna merge this and incorporate it into the new code :+1:  Thanks again!

**Pull request merged**
